apiVersion: v1
kind: ConfigMap
metadata:
    name: nignx-proxy-config
data:
    nginx-proxy.conf: 
        server  {
            listen 80;
            server_name www.pjb.com;
            location / {
                proxy_set_header Host $host;
                proxy_pass http://10.0.10.8;
             }
        }
