apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cicd-deploy
  namespace: abc
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx-cicd
        image: 10.0.16.140/lemonhope97/nginx-conf:5
        ports:
        - containerPort: 80
