apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cicd-deploy
  namespace: abc
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx-cicd
        image: nginx
        ports:
        - containerPort: 80
