apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: pjb-hpa
spec:
    maxReplicas: 10
    metrics:
    -   resource:
            name: cpu
            trarget:
                averageUtilization: 70
                type: Utilization
        type: Resource
    minReplicas: 2
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment 
        name: pjb-deploy